# Generated by Django 2.1.4 on 2019-01-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_card_cardmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardManager',
        ),
        migrations.AddField(
            model_name='card',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
