# Generated by Django 2.1.4 on 2019-01-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Images',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
