# Generated by Django 2.1.4 on 2019-01-04 01:24

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path),
        ),
    ]
