# Generated by Django 2.1.4 on 2019-01-04 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190103_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Images',
            new_name='image',
        ),
    ]
